name: Create solution from template
on:
  push:
    branches:
      master
jobs:
  CreateSolution:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.head_ref }}
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: | 
          3.1.x
          6.0.x
    - name: Install template
      run: dotnet new --install Staticsoft.Template.Library
    - name: Create solution
      run: dotnet new staticsoft-lib -n ${{ github.event.repository.name }}
    - name: Delete conflicting directories
      run: rm -rf .github
    - name: Move library files to root directory
      run: mv ${{ github.event.repository.name }}/{.[!.],}* .
    - name: Remove empty directory
      run: rmdir ${{ github.event.repository.name }}
      